### ISSUE TITLE
Placing Netherrack makes no sound

### ISSUE THREAD

**Issue by socklessthing** [BTW-Community/Deco-Addon-2#27]
When placing Netherrack in the Nether and not having the 1.16 sounds installed makes no block placing sounds.
Hope this isn't already known.

**Comment by ammoore00** [comment]
Yeah that's part of a larger issue with the custom sounds in multiplayer. Still investigating fixes

**Comment by ammoore00** [comment]
Closing this as the new sounds have been disabled in 4.X, pending the 1.6 update which will fix basically everything that was wrong with the old sound system.
